[project]
name = "utils"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "proteusiq", email = "praysonpi@gmail.com" }
]
dependencies = [
]

requires-python = ">= 3.11"

